# Generated by Django 4.0.6 on 2022-07-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugat',
        ),
    ]
