# Generated by Django 4.0.6 on 2022-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_delete_lugat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vide_title', models.CharField(max_length=150)),
                ('vdieo', models.FileField(upload_to='')),
                ('vide_descraption', models.TextField(max_length=700)),
            ],
        ),
    ]
