# Generated by Django 4.0.6 on 2022-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vdieo',
            field=models.FileField(upload_to='media'),
        ),
    ]
