# Generated by Django 4.0.6 on 2022-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_video_vdieo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vdieo',
            field=models.FileField(upload_to=''),
        ),
    ]
