# Generated by Django 4.0.6 on 2022-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_video_vdieo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vide_title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
