# Generated by Django 4.0.6 on 2022-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_video_vide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vdieo',
            field=models.FilePathField(),
        ),
    ]
