# Generated by Django 4.0.6 on 2022-07-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_video_vdieo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vdieo',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vide_title',
            new_name='img_title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vide_descraption',
            new_name='vide_aboute',
        ),
    ]
