# Generated by Django 4.0.6 on 2022-07-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_rename_vdieo_video_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='UploadImg',
        ),
    ]
