# Generated by Django 4.0.6 on 2022-07-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_rename_video_uploadimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimg',
            old_name='vide_aboute',
            new_name='aboute',
        ),
    ]
