# Generated by Django 4.0.6 on 2022-07-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_rename_vide_aboute_uploadimg_aboute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='aboute',
        ),
    ]
