# Generated by Django 4.0.6 on 2022-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_myuser_bio_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
