# Generated by Django 4.0.6 on 2022-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(default='no bio yet', max_length=70),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
