# Generated by Django 4.0.6 on 2022-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_alter_myuser_bio_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(max_length=70),
        ),
    ]
