# Generated by Django 4.0.6 on 2022-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_alter_myuser_email_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=70, null=True)),
                ('telegram', models.CharField(blank=True, max_length=70, null=True)),
                ('instagram', models.CharField(blank=True, max_length=70, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
