# Generated by Django 4.0.6 on 2022-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AddField(
            model_name='myuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pinterest',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
