# Generated by Django 4.0.6 on 2022-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_delete_social_myuser_facebook_myuser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
