# Generated by Django 4.0.6 on 2022-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_myuser_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=70, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('facebook', models.CharField(blank=True, max_length=70, null=True)),
                ('telegram', models.CharField(blank=True, max_length=70, null=True)),
                ('instagram', models.CharField(blank=True, max_length=70, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=70, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='img',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
