# Generated by Django 4.0.6 on 2022-08-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
