# Generated by Django 4.0.6 on 2022-08-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0039_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
