# Generated by Django 4.0.6 on 2022-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0041_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.CharField(blank=True, max_length=70, null=True)),
                ('facebook', models.CharField(blank=True, max_length=70, null=True)),
                ('telegram', models.CharField(blank=True, max_length=70, null=True)),
                ('instagram', models.CharField(blank=True, max_length=70, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=70, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='img',
        ),
    ]
