# Generated by Django 4.0.6 on 2022-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0043_delete_profile_myuser_bio_myuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='img_via_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
