# Generated by Django 4.0.6 on 2022-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0044_uploadimg_img_via_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='img_via_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
