# Generated by Django 4.0.6 on 2022-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0045_alter_uploadimg_img_alter_uploadimg_img_via_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimg',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
