# Generated by Django 4.0.6 on 2022-08-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0046_alter_uploadimg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='img_via_url',
        ),
    ]
