# Generated by Django 4.0.6 on 2022-08-05 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_remove_uploadimg_img_via_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='creat_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
