# Generated by Django 4.0.6 on 2022-08-05 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0048_uploadimg_creat_time_uploadimg_likes_uploadimg_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
