# Generated by Django 4.0.6 on 2022-08-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0049_remove_uploadimg_user_uploadimg_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImg',
            new_name='Post',
        ),
    ]
