# Generated by Django 4.1 on 2022-08-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='img',
            new_name='profile_pic',
        ),
    ]
