# Generated by Django 4.1 on 2022-08-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_modform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModForm',
        ),
    ]
