# Generated by Django 4.1 on 2022-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_delete_modform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=70)),
                ('img', models.ImageField(default='userprofile.png', upload_to='profile_pic')),
            ],
        ),
    ]
