# Generated by Django 4.1 on 2022-08-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_profile_cust_user_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profile_pic',
        ),
    ]
