# Generated by Django 4.0.6 on 2022-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_remove_myuser_bio_remove_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creat_time',
            field=models.DateField(default='12:3153'),
        ),
    ]
