# Generated by Django 4.0.6 on 2022-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_alter_post_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creat_time',
            field=models.DateField(default='12:34:02'),
        ),
    ]
